name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          echo "Current directory contents:"
          ls -R

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Debug Build Output
        run: |
          echo "Build directory contents:"
          ls -la build
          echo "Public directory contents:"
          ls -la public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true