name: Deploy to GitHub Pages

on:
  push:
    branches: [feat/basic-deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Export
        run: |
          # Clean previous builds
          rm -rf build dist public/build

          # Build with static export
          REMIX_EXPORT=1 npm run build
          
          # Debug output
          echo "Build directory contents:"
          ls -la build
          echo "Public directory contents:"
          ls -la public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true